spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/med_app
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                order_updates: true
                order_inserts: true
                ddl-auto: create
                default-schema: med_api
        show-sql: true
    flyway:
        locations: classpath:db/migration
        schemas: med_api
